version: '3.1'
services:
  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "$USER"
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql
