default: &default
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://localhost/graphql_workshop_development") %>

test:
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://localhost/graphql_workshop_test") %>

production:
  <<: *default
